In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


In [0]:
a= 10
s = 'hello'

In [6]:
t1 = tf.constant(a)
t1

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [5]:
type(t1)

tensorflow.python.framework.ops.Tensor

In [0]:
t2 = tf.constant(s)

In [8]:
t2

<tf.Tensor 'Const_2:0' shape=() dtype=string>

In [9]:
type(t2)

tensorflow.python.framework.ops.Tensor

In [0]:
# Tensorflow uses the numpy librabries, tensorflow do not have its own integrers and strings datatype, it takes datatypes from Numpy array librabry

# session object of tensorflow brings/extracts the value from the tensorflow objects 
# which are created using contant object function in the tensorflow


In [0]:
sess = tf.Session()

In [11]:
sess.run(t1)

10

In [12]:
sess.run(t2)

b'hello'

In [13]:
type(sess.run(t1)) # Tensorflow uses the numpy librabries

numpy.int32

In [14]:
type(sess.run(t2)) # Tensorflow uses the numpy librabries

bytes

In [0]:
x = tf.constant(11)
y = tf.constant(12)

In [21]:
sess.run(x+y)

23

In [22]:
sess.run(t12)


12

In [0]:
# tensorflow do not have its garbage collector
# in order to use the session object for sometime use it with 'with' keyword , it will only then destroy the session object

In [25]:
with tf.Session() as sess:
  print(sess.run(x+y))
  print(sess.run(x-y))
  print(sess.run(x*y))
  print(sess.run(x/y))

23
-1
132
0.9166666666666666


In [0]:
# tensorflow is written in 'C' language

# tensorflow objects are made using 'constant' or the 'placeholder'
# constant uses the value of variable and then makes the object
# whereas placeholder requires the datatype of the value to make objects

In [0]:
p = tf.placeholder(tf.int32)
q = tf.placeholder(tf.int32)

In [28]:
type(p)

tensorflow.python.framework.ops.Tensor

In [29]:
type(q)

tensorflow.python.framework.ops.Tensor

In [0]:
# tensorflow has its own 'add' function

In [0]:
addition = tf.add(p,q)
substraction= tf.subtract(p,q)
multiple= tf.multiply(p,q)
d = {p:30,q:10}

In [40]:
with tf.Session() as sess:
  print(sess.run(addition, {p:10, q:20}))  # the arguments in tensorflow are given using dictionary
  print(sess.run(substraction, {p:20,q:30}))
  print(sess.run(multiple, d))

30
-10
300


In [0]:
b = tf.constant([1,2,3,4], shape=[2,2])
c = tf.constant([4,5,6,7], shape=[2,2])

matrxMul = tf.matmul(b,c)

In [43]:
with tf.Session() as sess:
  print(sess.run(matrxMul))

[[16 19]
 [36 43]]


In [63]:
b1 = tf.constant(np.arange(1,3).reshape(1,2))
c1 = tf.constant(np.arange(4,6).reshape(2,1))

with tf.Session() as sess:
  print(sess.run(tf.matmul(b1,c1)))

# result will be a [1,1] matrix

[[14]]


In [0]:

import numpy as np
s = np.arange(1,5)
s = s.reshape(2,2)
t = np.arange(6,10)
t=t.reshape(2,2)

In [0]:
m = tf.placeholder(tf.int32, shape=[2,2])
n= tf.placeholder(tf.int32, shape=[2,2])
matmultiplication = tf.matmul(m,n)

In [62]:
with tf.Session() as sess:
  print(sess.run(matmultiplication, {m:s, n:t}))


[[22 25]
 [50 57]]


In [64]:
m1 = tf.placeholder(tf.int32, shape=[None,2]) # matrix [any rows *2]
n1= tf.placeholder(tf.int32, shape=[2,None]) # matrix [2*any columns]
matmultiplication = tf.matmul(m1,n1)

s1 = np.arange(1,9).reshape(4,2)
t1 = np.arange(2,10).reshape(2,4)
with tf.Session() as sess:
  print(sess.run(matmultiplication, {m1:s1, n1:t1}))
# result will be a [4,4] matrix

[[ 14  17  20  23]
 [ 30  37  44  51]
 [ 46  57  68  79]
 [ 62  77  92 107]]
